[package]
name = "cc"
version = "0.1.0"
edition = "2021"

[lib]
name = "cc"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = { version = "1", features = ["preserve_order", "arbitrary_precision"] }
jni = "0.21"
getrandom = "0.3"
ryu = "1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
